### ISSUE TITLE
Please allow the dependency primitive 0.8 (and 0.9)

### ISSUE THREAD

**Issue by DaveBarton** [konsumlamm/extended-containers#8]
Thanks!

**Comment by DaveBarton** [comment]
I withdraw this request, as the pqueue package is faster for my use case.

**Comment by konsumlamm** [comment]
Yeah, `pqueue` should generally be faster, I updated the readme to link to alternatives.

**Comment by DaveBarton** [comment]
Excellent, thanks!

You are very impressive in many ways, and we Haskell programmers are lucky to have you.
